version: '3.9'

services:

  sample:
    container_name: samplereact
    image: samplereact_img
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
        - type: bind
          source: .
          target: /opt/web
        - '/opt/web/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true