# pull official base image
## FROM node:alpine
FROM node:15.9.0-alpine3.11 AS builder
LABEL version="1.0"
LABEL description="cra react dev image"
LABEL maintainer = ["geministars@yandex.ru", "artigeministars@gmail.com"]

# set working directory
WORKDIR /opt/web



# install app dependencies
COPY package.json ./
COPY package-lock.json ./
RUN npm install

# add `/app/node_modules/.bin` to $PATH
ENV PATH="/opt/web/node_modules/.bin:$PATH"
# ENV PATH /app/node_modules/.bin:$PATH
RUN npm install
RUN npm install react-scripts@3.4.1 -g 
# --silent
RUN npm audit fix
# add app
COPY . ./
# RUN  chown -R node:node /app/node_modules
# RUN  chown -R node:node ~/.npm
# RUN  chown -R node:node /usr/local
# RUN chown -R node:node /usr/local/lib/node_modules
# RUN mkdir /app/node_modules/.cache && chown -R node:node /app/node_modules/.cache
# RUN sudo chown [username] .npm
EXPOSE 3000
# start app
CMD ["npm", "start"]